datagrid:
    accounts-grid:
        extended_entity_name: %mekit_account.account.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_account_account_view
            query:
                select:
                    - a.id
                    - a.name
                    - accountType.label as type
                    - accountState.label as state
                    - accountIndustry.label as industry
                    - accountSource.label as source
                    - CONCAT(assignees.firstName, CONCAT(' ', assignees.lastName)) as assigneeFullName
                from:
                    - { table: %mekit_account.account.entity.class%, alias: a }
                join:
                    left:
                        - { join: a.type, alias: accountType }
                        - { join: a.state, alias: accountState }
                        - { join: a.industry, alias: accountIndustry }
                        - { join: a.source, alias: accountSource }
                        - { join: a.users, alias: assignees }

        columns:
            name:
                label:         mekit.account.name.label
            type:
                label:         mekit.account.type.label
            state:
                label:         mekit.account.state.label
            industry:
                label:         mekit.account.industry.label
            source:
                label:         mekit.account.source.label
            assigneeFullName:
                label:         mekit.account.users.label

        sorters:
            columns:
                name:
                    data_name: a.name
                type:
                    data_name: type
                state:
                    data_name: state
                industry:
                    data_name: industry
                source:
                    data_name: source


        filters:
            columns:
                name:
                    type:      string
                    data_name: a.name
                type:
                    type:      entity
                    data_name: accountType.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'ACCOUNT_TYPE'
                        multiple: true
                state:
                    type:      entity
                    data_name: accountState.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'ACCOUNT_STATE'
                        multiple: true
                industry:
                    type:      entity
                    data_name: accountIndustry.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'ACCOUNT_INDUSTRY'
                        multiple: true
                source:
                    type:      entity
                    data_name: accountSource.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'ACCOUNT_SOURCE'
                        multiple: true
                assigneeFullName:
                    type:      assignee
                    data_name: assignees.id

        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_account_view
                params:     [ id ]
            update_link:
                type:       url
                route:      mekit_account_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      mekit_api_delete_account
                params:     [ id ]

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_account_account_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  mekit_account_account_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  mekit_account_account_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

        mass_actions:
            merge:
                type: merge
                entity_name: %mekit_account.account.entity.class%
                data_identifier: a.id
            delete:
                type: delete
                entity_name: %mekit_account.account.entity.class%
                data_identifier: a.id
                acl_resource: mekit_account_account_delete
                label: oro.grid.action.delete
                icon: trash

        options:
            entityHint: account
            export: true


    # 1) Extending datagrid MUST declare the FROM table with alias "baseEntity" which MUST have "accounts" relationship
    # 2) parameter "ref_id" identifying the "baseEntity" must be defined
    accounts-related-generic:
        extended_entity_name: %mekit_account.account.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_account_account_view
            query:
                select:
                    - a.id
                    - a.name
                join:
                    inner:
                        - { join: baseEntity.accounts, alias: a }
                where:
                    and:
                        - baseEntity.id = :ref_id
            bind_parameters:
                - ref_id
        columns:
            name:
                label:         mekit.account.name.label
        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_account_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  mekit_account_account_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true

    accounts-related-users:
        extends: crm-related-users
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

    accounts-related-contacts:
        extends: contacts-related-generic
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

    accounts-related-projects:
        extends: projects-related-generic
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

    accounts-related-tasks:
        extends: tasks-related-generic
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

    accounts-related-calls:
        extends: calls-related-generic
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

    accounts-related-meetings:
        extends: meetings-related-generic
        source:
            query:
                from:
                    - { table: %mekit_account.account.entity.class%, alias: baseEntity }

