datagrid:
    accounts-grid:
        extended_entity_name: %mekit_account.account.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_account_account_view
            query:
                select:
                    - a.id
                    - a.name
                    - a.vatid
                    - accountType.label as type
                    - accountState.label as state
                    - accountIndustry.label as industry
                    - a.createdAt
                    - a.updatedAt
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                from:
                    - { table: %mekit_account.account.entity.class%, alias: a }
                join:
                    left:
                        - { join: a.owner, alias: accountOwner }
                        - { join: a.type, alias: accountType }
                        - { join: a.state, alias: accountState }
                        - { join: a.industry, alias: accountIndustry }

        columns:
            name:
                label:         mekit.account.name.label
            vatid:
                label:         mekit.account.vatid.label
            type:
                label:         mekit.account.type.label
            state:
                label:         mekit.account.state.label
            industry:
                label:         mekit.account.industry.label
            ownerName:
                label:         mekit.account.owner.label

        sorters:
            columns:
                name:
                    data_name: a.name
                ownerName:
                    data_name: ownerName
                type:
                    data_name: type

        filters:
            columns:
                name:
                    type:      string
                    data_name: a.name
                ownerName:
                    type:      string
                    data_name: ownerName
                type:
                    type:      entity
                    data_name: accountType.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilder_ACCOUNT_TYPE
                        multiple: true
                state:
                    type:      entity
                    data_name: accountState.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilder_ACCOUNT_STATE
                        multiple: true
                industry:
                    type:      entity
                    data_name: accountIndustry.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilder_ACCOUNT_INDUSTRY
                        multiple: true

        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_account_view
                params:     [ id ]
            update_link:
                type:       url
                route:      mekit_account_update
                params:     [ id ]

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_account_account_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  mekit_account_account_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
        mass_actions:
            merge:
                type: merge
                entity_name: %mekit_account.account.entity.class%
                data_identifier: a.id
        options:
            entityHint: account
            export: true

    accounts-select-grid:
        extended_entity_name: %mekit_account.account.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_account_account_view
            query:
                select:
                    - a.id
                    - a.name
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                from:
                    - { table: %mekit_account.account.entity.class%, alias: a }
                join:
                    left:
                        - { join: a.owner, alias: accountOwner }
        properties:
            id: ~
        columns:
            name:
                label:   mekit.account.name.label
            ownerName:
                label:   mekit.account.owner.label
        sorters:
            columns:
                name:
                    data_name: a.name
                ownerName:
                    data_name: ownerName
        filters:
            columns:
                name:
                    type:      string
                    data_name: a.name
                ownerName:
                    type:      string
                    data_name: ownerName
        options:
            entityHint: account
