parameters:
    mekit_account.importexport.template_fixture.account.class: Mekit\Bundle\AccountBundle\ImportExport\TemplateFixture\AccountFixture
    mekit_account.importexport.strategy.account.add_or_replace.class: Mekit\Bundle\AccountBundle\ImportExport\Strategy\AccountAddOrReplaceStrategy

services:
    mekit_account.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    mekit_account.importexport.template_fixture.data_converter.account:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    mekit_account.importexport.strategy.account.add_or_replace:
        class: %mekit_account.importexport.strategy.account.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    mekit_account.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@mekit_account.importexport.data_converter]]
             - [setStrategy, [@mekit_account.importexport.strategy.account.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %mekit_account.account.entity.class%, alias: mekit_account.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %mekit_account.account.entity.class%, alias: mekit_account.add_or_replace }

    # Export processor
    mekit_account.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mekit_account.importexport.data_converter]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %mekit_account.account.entity.class%, alias: mekit_account }

    mekit_account.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mekit_account.importexport.template_fixture.data_converter.account]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %mekit_account.account.entity.class%, alias: mekit_account }

    mekit_account.importexport.template_fixture.account:
        class: %mekit_account.importexport.template_fixture.account.class%
        tags:
            - { name: oro_importexport.template_fixture }
