parameters:
    mekit_account.account.entity.class:                         Mekit\Bundle\AccountBundle\Entity\Account

services:
    mekit_account.autocomplete.account.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %mekit_account.account.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: mekit_account_search, acl_resource: mekit_account_account_view }

