datagrid:
    tasks-grid:
        extended_entity_name: %mekit_task.task.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_event_view
            query:
                select:
                    - t.id
                    - t.name
                    - e.id as eventId
                    - e.type
                    - e.startDate
                    - e.endDate
                    - e.duration
                    - eventState.label as state
                    - eventPriority.label as priority
                from:
                    - { table: %mekit_task.task.entity.class%, alias: t }
                join:
                    left:
                        - { join: t.event, alias: e }
                        - { join: e.owner, alias: eventOwner }
                        - { join: e.state, alias: eventState }
                        - { join: e.priority, alias: eventPriority }

        columns:
            type_icon:
                data_name:      type
                label:          mekit.event.type.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventIcon.html.twig
            name:
                label:          mekit.task.name.label
            state:
                label:         mekit.event.state.label
            startDate:
                label:         mekit.event.start_date.label
                frontend_type: datetime
            endDate:
                label:         mekit.event.end_date.label
                frontend_type: datetime
            duration:
                label:         mekit.event.duration.label
            priority:
                label:         mekit.event.priority.label

        properties:
            id:             ~
            eventId:        ~
            view_link:
                type:       url
                route:      mekit_task_view
                params:     [ id ]
            update_link:
                type:       url
                route:      mekit_task_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      mekit_api_delete_event
                params:
                    id: eventId

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_event_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  mekit_task_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  mekit_event_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

        sorters:
            columns:
                name:
                    data_name: t.name
                state:
                    data_name: eventState.label
                startDate:
                    data_name: e.startDate
                endDate:
                    data_name: e.endDate
                duration:
                    data_name: e.duration
                priority:
                    data_name: eventPriority.label

        filters:
            columns:
                name:
                    type:      string
                    data_name: t.name
                state:
                    type:      entity
                    data_name: eventState.id
                    options:
                        field_options:
                            class:     MekitListBundle:ListItem
                            property:  label
                            query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                            attr:
                                group_name: 'EVENT_STATE'
                            multiple: true
                priority:
                    type:      entity
                    data_name: eventPriority.id
                    options:
                        field_options:
                            class:     MekitListBundle:ListItem
                            property:  label
                            query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                            attr:
                                group_name: 'EVENT_PRIORITY'
                            multiple: true

    # 1) Extending datagrid MUST declare the FROM table with alias "baseEntity" which MUST have "tasks" relationship
    # 2) parameter "ref_id" identifying the "baseEntity" must be defined
    tasks-related-generic:
        extended_entity_name: %mekit_task.task.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_event_view
            query:
                select:
                    - t.id
                    - t.name
                    - e.startDate
                    - e.endDate
                join:
                    inner:
                        - { join: baseEntity.tasks, alias: t }
                        - { join: t.event, alias: e }
                where:
                    and:
                        - baseEntity.id = :ref_id
            bind_parameters:
                - ref_id
        columns:
            name:
                label:         mekit.task.name.label
            startDate:
                label:         mekit.event.start_date.label
                frontend_type: datetime
            endDate:
                label:         mekit.event.end_date.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_task_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  mekit_event_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true

    tasks-related-users:
        extends: crm-related-users
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }

    tasks-related-accounts:
        extends: accounts-related-generic
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }

    tasks-related-contacts:
        extends: contacts-related-generic
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }

    tasks-related-projects:
        extends: projects-related-generic
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }

    tasks-related-calls:
        extends: calls-related-generic
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }

    tasks-related-meetings:
        extends: meetings-related-generic
        source:
            query:
                from:
                    - { table: %mekit_task.task.entity.class%, alias: baseEntity }


    worklogs-related-to-task:
        extended_entity_name: %mekit_task.worklog.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_event_view
            query:
                select:
                    - wl.id
                    - wl.registrationDate
                    - wl.duration
                    - wl.description
                    - wlOwner.firstName as ownerName
                from:
                    - { table: %mekit_task.worklog.entity.class%, alias: wl }
                join:
                    inner:
                        - { join: wl.task, alias: t }
                        - { join: wl.owner, alias: wlOwner }
                where:
                    and:
                        - t.id = :ref_id
            bind_parameters:
                - ref_id
        columns:
            registrationDate:
                label:         mekit.task.worklog.registration_date.label
                frontend_type: datetime
            duration:
                label:         mekit.task.worklog.duration.label
            ownerName:
                label:         mekit.task.worklog.owner.label
            description:
                label:         mekit.task.worklog.description.label
#        properties:
#            id: ~
#            view_link:
#                type:       url
#                route:      mekit_task_view
#                params:     [ id ]
#        actions:
#            view:
#                type:          navigate
#                acl_resource:  mekit_event_view
#                label:         oro.grid.action.view
#                icon:          eye-open
#                link:          view_link
#                rowAction:     true