datagrid:
    tasks-grid:
        extended_entity_name: %mekit_task.task.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_event_view
            query:
                select:
                    - c.id as linkRefId
                    - c.description
                    - e.name
                    - e.type
                    - e.startDate
                    - e.endDate
                    - e.duration
                    - eventState.label as state
                    - eventPriority.label as priority
                from:
                    - { table: %mekit_task.task.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.event, alias: e }
                        - { join: e.owner, alias: eventOwner }
                        - { join: e.state, alias: eventState }
                        - { join: e.priority, alias: eventPriority }

        columns:
            type_icon:
                data_name:      type
                label:          mekit.event.type.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventIcon.html.twig
            linked_name:
                data_name:      type
                label:          mekit.event.name.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventLink.html.twig
                context:
                    config_route_key:     view_route_name
            state:
                label:         mekit.event.state.label
            startDate:
                label:         mekit.event.start_date.label
                frontend_type: datetime
            endDate:
                label:         mekit.event.end_date.label
                frontend_type: datetime
            duration:
                label:         mekit.event.duration.label
            priority:
                label:         mekit.event.priority.label

        sorters:
            columns:
                linked_name:
                    data_name: e.name
                state:
                    data_name: eventState.label
                startDate:
                    data_name: e.startDate
                endDate:
                    data_name: e.endDate
                duration:
                    data_name: e.duration
                priority:
                    data_name: eventPriority.label

        filters:
            columns:
                linked_name:
                    type:      string
                    data_name: e.name
                state:
                    type:      entity
                    data_name: eventState.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'EVENT_STATE'
                        multiple: true
                priority:
                    type:      entity
                    data_name: eventPriority.id
                    options:
                      field_options:
                        class:     MekitListBundle:ListItem
                        property:  label
                        query_builder: @mekit_list.datagrid_helper->getListItemQueryBuilderForGroup
                        attr:
                            group_name: 'EVENT_PRIORITY'
                        multiple: true

    task-activity-grid:
        extended_entity_name: %mekit_task.task.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_event_view
            query:
                select:
                    - c.id
                    - c.description
                    - e.name
                    - e.type
                    - e.startDate
                    - e.endDate
                    - e.duration
                    - eventState.label as state
                    - eventPriority.label as priority
                from:
                    - { table: %mekit_task.task.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.event, alias: e }
                        - { join: e.owner, alias: eventOwner }
                        - { join: e.state, alias: eventState }
                        - { join: e.priority, alias: eventPriority }

        columns:
            type_icon:
                data_name:      type
                label:          mekit.event.type.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventIcon.html.twig
            name:
                label:         mekit.event.name.label
            state:
                label:         mekit.event.state.label
            startDate:
                label:         mekit.event.start_date.label
                frontend_type: datetime
            endDate:
                label:         mekit.event.end_date.label
                frontend_type: datetime
            duration:
                label:         mekit.event.duration.label
            priority:
                label:         mekit.event.priority.label

        sorters:
        filters:


    tasks-related-relationship:
        extends: relationship-related-element-source-logic
        source:
            acl_resource:   mekit_event_view
            query:
                select:
                    - e.id
                    - ev.name as eventName
                from:
                   - { table: %mekit_task.task.entity.class%, alias: e }
                join:
                    left:
                        - { join: e.event, alias: ev }

        columns:
            id:
                label:        mekit.task.id.label
            eventName:
                label:        mekit.event.name.label

        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_task_view
                params:     [ id ]

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_event_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
