parameters:
    mekit_task.manager.api.class:                         Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    mekit_task.type.task.class:                           Mekit\Bundle\TaskBundle\Form\Type\TaskType
    mekit_task.type.worklog.class:                        Mekit\Bundle\TaskBundle\Form\Type\WorklogType
    mekit_task.type.worklog.api.class:                    Mekit\Bundle\TaskBundle\Form\Type\WorklogApiType

    mekit_task.handler.task.class:                        Mekit\Bundle\TaskBundle\Form\Handler\TaskHandler
    mekit_task.handler.worklog.class:                     Mekit\Bundle\TaskBundle\Form\Handler\WorklogHandler

services:
    mekit_task.task.manager.api:
        class: %mekit_task.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mekit_task.task.entity.class%
            - @doctrine.orm.entity_manager

    mekit_task.form.task:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_task_form", "mekit_task", null]

    mekit_task.form.type.task:
        class: %mekit_task.type.task.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
            - @mekit_list.form_helper
        tags:
            - { name: form.type, alias: mekit_task }

    mekit_task.form.handler.task:
        class: %mekit_task.handler.task.class%
        scope: request
        arguments:
            - @mekit_task.form.task
            - @request
            - @doctrine.orm.entity_manager


    mekit_task.worklog.manager.api:
        class: %mekit_task.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mekit_task.worklog.entity.class%
            - @doctrine.orm.entity_manager

    mekit_task.form.worklog.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_worklog_api", "mekit_worklog_api", null]

    mekit_task.form.type.worklog.api:
        class: %mekit_task.type.worklog.api.class%
        arguments:
            - @router
        tags:
            - { name: form.type, alias: mekit_worklog_api }

    mekit_task.form.handler.worklog.api:
        class: %mekit_task.handler.worklog.class%
        scope: request
        arguments:
            - @mekit_task.form.worklog.api
            - @request
            - @doctrine.orm.entity_manager
