items:
    mekit_task_create_button:
        template: MekitTaskBundle:Task/placeholders:addTaskButton.html.twig
        applicable: @mekit_task.placeholder.filter->isTaskAssociationEnabled($entity$)
        acl: mekit_task_create

placeholders:
    view_navButtons_after:
        items:
            mekit_task_create_button:
                order:  200
