parameters:
#    mekit_task.example.class: Mekit\Bundle\TaskBundle\Example

services:
#    mekit_task.example:
#        class: %mekit_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
