mekit_call_bundle:
    resource:     "@MekitCallBundle/Controller"
    type:         annotation
    prefix:       /call

mekit_call_bundle_api:
    resource: "@MekitCallBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
