parameters:
    mekit_list.manager.api.class:                              Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    mekit_list.type.listgroup.class:                           Mekit\Bundle\ListBundle\Form\Type\ListGroupType
    mekit_list.type.listitem.class:                            Mekit\Bundle\ListBundle\Form\Type\ListItemType
    mekit_list.type.listitem.select.class:                     Mekit\Bundle\ListBundle\Form\Type\ListItemSelectType

    mekit_list.handler.listgroup.class:                        Mekit\Bundle\ListBundle\Form\Handler\ListGroupHandler
    mekit_list.handler.listitem.class:                         Mekit\Bundle\ListBundle\Form\Handler\ListItemHandler

services:
    # ListGroup
    mekit_list.listgroup.manager.api:
        class: %mekit_list.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mekit_list.listgroup.entity.class%
            - @doctrine.orm.entity_manager

    mekit_list.form.listgroup:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_listgroup_form", "mekit_listgroup", null]

    mekit_list.form.type.listgroup:
        class: %mekit_list.type.listgroup.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: mekit_listgroup }

    mekit_list.form.handler.listgroup:
        class: %mekit_list.handler.listgroup.class%
        scope: request
        arguments:
            - @mekit_list.form.listgroup
            - @request
            - @doctrine.orm.entity_manager


    # ListItem
    mekit_list.listitem.manager.api:
        class: %mekit_list.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mekit_list.listitem.entity.class%
            - @doctrine.orm.entity_manager

    mekit_list.form.listitem:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_listitem_form", "mekit_listitem", null]

    mekit_list.form.type.listitem:
        class: %mekit_list.type.listitem.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: mekit_listitem }

    mekit_list.form.handler.listitem:
        class: %mekit_list.handler.listitem.class%
        scope: request
        arguments:
            - @mekit_list.form.listitem
            - @request
            - @doctrine.orm.entity_manager

    #ListItem Selector
    mekit_list.form.type.listitem_select:
        class: %mekit_list.type.listitem.select.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @translator
        tags:
            - { name: form.type, alias: mekit_listitem_select }