Mekit\Bundle\ListBundle\Entity\ListItem:
    alias: mekit_listitem
    label: mekit.list.entity_item_plural_label
    route:
        name: mekit_listitem_view
        parameters:
            id: id
    search_template: MekitListBundle:ListItem:searchResult.html.twig
    fields:
        -
            name:                   label
            target_type:            text
            target_fields:          [label]
