parameters:
    mekit_list.listgroup.entity.class:                         Mekit\Bundle\ListBundle\Entity\ListGroup
    mekit_list.listitem.entity.class:                          Mekit\Bundle\ListBundle\Entity\ListItem

services:
