parameters:
#    mekit_list.example.class: Mekit\Bundle\ListBundle\Example

services:
#    mekit_list.example:
#        class: %mekit_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
