Mekit\Bundle\ListBundle\Entity\ListGroup:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 32
            - Regex:
                pattern: '/^[A-Z][A-Z0-9_]*$/'
                message: Only uppercase letters, numbers and underscore(_)!
        label:
            - NotBlank: ~
            - Length:
                max: 255

    constraints:
        - Callback: [validate]

Mekit\Bundle\ListBundle\Entity\ListItem:
    properties:
        label:
            - NotBlank: ~
            - Length:
                max: 255
