mekit_worklog_bundle:
    resource:     "@MekitWorklogBundle/Controller"
    type:         annotation
    prefix:       /worklog

mekit_worklog_bundle_api:
    resource: "@MekitWorklogBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest