filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'
    - 'tests/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_mess_detector: true
  php_cs_fixer: true
  php_code_sniffer: true
  php_loc: true
  php_cpd: true
  php_code_coverage: false
  external_code_coverage:
      timeout: 900

checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php: 5.5.12
  dependencies:
    before:
    override:
      # skip dependency check - it takes a lot of time and it will be done on travis anyways
      # - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800 }
      - { command: 'true' }
    after:
  project_setup:
  tests:
      # skip phpunit tests - will be done on travis anyways
      - { command: 'true' }