filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'
    - 'tests/*'
    - 'src/Mekit/Bundle/*Bundle/Tests/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_mess_detector: true
  php_cs_fixer: true
  php_code_sniffer: true
  php_loc: true
  php_cpd: true
  php_code_coverage: false
  external_code_coverage:
      timeout: 1800
      runs: 2

checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php: 5.5.12
  dependencies:
    before:
    override:
#      - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800, only_if: 'test -e composer.lock' }
#      - { command: 'true' }
    after:
  project_setup:
  tests:
