filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'
    - 'tests/*'
    - 'src/Mekit/Bundle/*Bundle/Tests/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_mess_detector: true
  php_cs_fixer: true
  php_code_sniffer: true
  php_loc: true
  php_cpd: true
  php_code_coverage: false
  external_code_coverage:
      timeout: 1800
      runs: 2

checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php:
      version: 5.5.12
      ini:
        'date.timezone': 'Europe/Rome'
  dependencies:
    before:
    override:
      - { command: 'mkdir -p ~/.composer' }
      - { command: 'cp .travis.composer.config.json ~/.composer/config.json' }
      - { command: 'composer create-project mekit/crm-platform --no-interaction', idle_timeout: 600 }
      - { command: 'rm -rf ./vendor' }
      - { command: 'rm -rf crm-platform/vendor/mekit' }
      - { command: 'mv crm-platform/vendor ./' }
      - { command: 'mv crm-platform/app ./' }
      - { command: 'mv crm-platform/web ./' }
      - { command: 'rm -rf crm-platform' }
      - { command: 'composer dump-autoload --optimize'}
      - { command: 'mv app/config/parameters_test.yml.dist app/config/parameters_test.yml' }
      - { command: 'mysql -e "CREATE DATABASE mekit_test;" -uroot' }
      - { command: 'app/console oro:install --env=test --force --organization-name Mekit --user-name admin --user-password admin --user-email admin@example.com --user-firstname Mekit --user-lastname Tester --sample-data n --application-url http://localhost/' }
      - { command: 'app/console doctrine:fixture:load --env=test --no-debug --append --no-interaction --fixtures ./vendor/oro/platform/src/Oro/Bundle/TestFrameworkBundle/Fixtures' }
#     - { command: 'composer install --prefer-source --no-interaction', idle_timeout: 1800 }
#     - { command: 'true' }
    after:
  tests:

application:
  type: none
  environment:
    php:
      version: 5.5.12
#  project_setup:
#    before:
#      - mysql -uroot -e 'CREATE DATABASE mekitcrm'
#    after:
