filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'
    - 'tests/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true

checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php: 5.5.12
