filter:
  excluded_paths:
    - 'app/*'
    - 'vendor/*'
    - 'web/*'
    - 'src/Mekit/Bundle/*Bundle/Tests/*'

tools:
  php_sim: true
  php_analyzer: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_changetracking: true
  php_mess_detector: true
  php_cs_fixer: true
  php_code_sniffer: true
  php_loc: true
  php_cpd: true
  php_code_coverage: false
  external_code_coverage:
      timeout: 1800
      runs: 2

checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php:
      version: 5.5.12
      ini:
        'date.timezone': 'Europe/Rome'
  dependencies:
    before:
      - { command: 'sh src/Mekit/Bundle/TestBundle/CI/Scrutinizer/build_dependencies_before.sh', idle_timeout: 600 }
    override:
     - { command: 'composer install --no-interaction', idle_timeout: 1800 }
    after:
  tests:
    override:
      - { command: 'true' }

application:
  type: none