language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/before_script.sh"

script:
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/script.sh"

after_script:
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/after_script.sh"

notifications:
    on_success: never
    on_failure: always
