language: php
php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer selfupdate
  - composer install --prefer-source --no-interaction
  - composer update

script:
  - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $COMPOSER_CACHE_DIR

notifications:
    on_success: never
    on_failure: always