language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/before_script.sh"

script:
  - phpunit -c phpunit.xml --coverage-clover=coverage.clover.unit
  # Find a way to skip running application installation + functional tests if unit tests fail
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/install_application.sh"
  - phpunit -c phpunit_functional.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover.unit

notifications:
    on_success: never
    on_failure: always
