language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - "/bin/bash src/Mekit/Bundle/TestBundle/CI/Travis/before_script.sh"

script:
  - phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    on_success: never
    on_failure: always
