datagrid:
    opportunities-grid:
        extended_entity_name: %mekit_opportunity.opportunity.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_opportunity_view
            query:
                select:
                    - o.id
                    - o.name
                    - o.amount
                    - o.probability
                    - Account.name as accountName
                from:
                    - { table: %mekit_opportunity.opportunity.entity.class%, alias: o }
                join:
                    inner:
                        - { join: o.account, alias: Account }
                groupBy: o.id
        columns:
            name:
                label:         mekit.opportunity.name.label
            accountName:
                label:         mekit.opportunity.account.label
            amount:
                label:         mekit.opportunity.amount.label
                frontend_type: currency
            probability:
                label:         mekit.opportunity.probability.label
                frontend_type: percent
        sorters:
            columns:
                name:
                    data_name: o.name
            default:
                name:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: o.name
        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_opportunity_view
                params:     [ id ]
            update_link:
                type:       url
                route:      mekit_opportunity_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      mekit_api_delete_opportunity
                params:     [ id ]

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_opportunity_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  mekit_opportunity_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  mekit_opportunity_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

        mass_actions:
            delete:
                type: delete
                entity_name: %mekit_opportunity.opportunity.entity.class%
                data_identifier: o.id
                acl_resource: mekit_opportunity_delete
                label: oro.grid.action.delete
                icon: trash
        options:
            entityHint: opportunity
            export: true
