parameters:
    mekit_opportunity.opportunity.entity.class:                       Mekit\Bundle\OpportunityBundle\Entity\Opportunity

services:
    mekit_opportunity.autocomplete.opportunity.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %mekit_opportunity.opportunity.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: mekit_opportunity, acl_resource: mekit_opportunity_view }