mekit_list_bundle:
    resource:     "@MekitListBundle/Controller"
    type:         annotation
    prefix:       /list

#mekit_list_api:
#    resource:     "@MekitListBundle/Controller/Api/Rest/ListController.php"
#    type:         rest
#    prefix:       api/rest/{version}/
#    requirements:
#        version:  latest|v1
#    defaults:
#        version:  latest