parameters:
    mekit_crm.relationship.manager.class:       Mekit\Bundle\CrmBundle\Relationship\RelationshipManager
    mekit_crm.filter.assignee.class:            Mekit\Bundle\CrmBundle\Filter\AssigneeFilter

services:
    mekit_crm.relationship.manager:
        class: %mekit_crm.relationship.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_entity.doctrine_helper

    mekit_crm.filter.assignee:
        class: %mekit_crm.filter.assignee.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: assignee }
