parameters:
    mekit_crm.relationship.manager.class:      Mekit\Bundle\CrmBundle\Relationship\RelationshipManager
#    mekit_crm.datagrid_helper.class:           Mekit\Bundle\CrmBundle\Datagrid\UserDatagridHelper

services:
    mekit_crm.relationship.manager:
        class: %mekit_crm.relationship.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_entity.doctrine_helper

#    mekit_crm.datagrid_helper:
#            class: %mekit_crm.datagrid_helper.class%
#            arguments:
#                - @mekit_crm.user_repository
#
#    mekit_crm.user_repository:
#        class: Doctrine\ORM\EntityRepository
#        factory_service: doctrine.orm.entity_manager
#        factory_method: getRepository
#        arguments:
#            - 'OroUserBundle:User'
#
