parameters:
    mekit_contact_info.address.manager.api.class:            Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    mekit_contact_info.address.entity.class:                 Mekit\Bundle\ContactInfoBundle\Entity\Address
    mekit_contact_info.email.entity.class:                   Mekit\Bundle\ContactInfoBundle\Entity\Email
    mekit_contact_info.phone.entity.class:                   Mekit\Bundle\ContactInfoBundle\Entity\Phone

services:
    # Address
    mekit_contact_info.address.manager.api:
        class: %mekit_contact_info.address.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %mekit_contact_info.address.entity.class%
            - @doctrine.orm.entity_manager
