mekit_opportunity_bundle:
    resource:     "@MekitOpportunityBundle/Controller"
    type:         annotation
    prefix:       /opportunity

mekit_opportunity_bundle_api:
    resource: "@MekitOpportunityBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest