datagrid:

    # filters out all entities of a given class which reference OR is referred to by a specific ReferenceableElement (entity_id)
    # USAGE:
    #   1) extending datagrid must define "referenceableElement" through inner join
    #   2) parameter "ref_el_id" must be defined - it will rappresent the id of the ReferenceableElement for which we are checking references/referrals
    # PROVIDES:
    # 1) filter on filter on "referenceableElement" having REFERENCES TO the referenceableElement identified by "ref_el_id"
    # 2) filter on filter on "referenceableElement" having REFERRALS FROM the referenceableElement identified by "ref_el_id"
    # 3) "referenceableElement_reference" and "referenceableElement_referral" through left join
    # 4) field("referenceDirection")+column("direction") with values: IN(if it is a reference) | OUT(if it is a referral)
    relationship-related-element-source-logic:
        source:
            type: orm
            query:
                select:
                    - CASE WHEN referenceableElement_reference IS NOT NULL THEN 'IN' ELSE 'OUT' END as referenceDirection
                join:
                    left:
                        - { join: referenceableElement.references, alias: referenceableElement_reference }
                        - { join: referenceableElement.referrals, alias: referenceableElement_referral }
                where:
                    and:
                        - (referenceableElement_reference.id = :ref_el_id OR referenceableElement_referral.id = :ref_el_id)
            bind_parameters:
                - ref_el_id
        columns:
            direction:
                data_name:      referenceDirection
                label:          mekit.relationship.direction.label
                type:           twig
                frontend_type:  html
                template:       MekitRelationshipBundle:Relationship:Datagrid/Property/directionIcon.html.twig
