oro_entity_config:
    relationship:
        entity:
            items:
                # indicates whether the entity is a referenceable element
                referenceable: # boolean
                    options:
                        priority:           250
                        default_value:      false
