parameters:
#    mekit_relationship.relationship.manager.api.class:               Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    mekit_relationship.type.relationship_select.class:               Mekit\Bundle\RelationshipBundle\Form\Type\RelationshipSelectType

#    mekit_relationship.handler.relationship.class:                   Mekit\Bundle\RelationshipBundle\Form\Handler\RelationshipHandler

services:
    mekit_relationship.form.type.relationship_select:
            class: %mekit_relationship.type.relationship_select.class%
            tags:
                - { name: form.type, alias: mekit_relationship_select }