parameters:
#    mekit_relationship.relationship.manager.api.class:                      Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    mekit_relationship.type.referenceable_element.class:                     Mekit\Bundle\RelationshipBundle\Form\Type\ReferenceableElementType
    mekit_relationship.type.reference_select.class:                          Mekit\Bundle\RelationshipBundle\Form\Type\ReferenceSelectType
    mekit_relationship.type.reference_select_collection.class:               Mekit\Bundle\RelationshipBundle\Form\Type\ReferenceSelectCollectionType

#    mekit_relationship.handler.relationship.class:                         Mekit\Bundle\RelationshipBundle\Form\Handler\RelationshipHandler

services:
    mekit_relationship.form.referenceable_element:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_referenceable_element_form", "mekit_referenceable_element", null]

    mekit_relationship.form.type.referenceable_element:
        class: %mekit_relationship.type.referenceable_element.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: mekit_referenceable_element }



    mekit_relationship.form.type.reference_select:
            class: %mekit_relationship.type.reference_select.class%
            arguments:
                - @mekit_relationship.form_helper
            tags:
                - { name: form.type, alias: mekit_reference_select }

    mekit_relationship.form.type.reference_select_collection:
        class: %mekit_relationship.type.reference_select_collection.class%
        tags:
             - { name: form.type, alias: mekit_reference_select_collection }

