parameters:
    mekit_relationship.type.relationship_assignment.class:                  Mekit\Bundle\RelationshipBundle\Form\Type\RelationshipAssignmentType
    mekit_relationship.type.referenceable_element.class:                    Mekit\Bundle\RelationshipBundle\Form\Type\ReferenceableElementType
    mekit_relationship.type.referenceable_element_multi_select2.class:      Mekit\Bundle\RelationshipBundle\Form\Type\ReferenceableElementMultiSelect2

    mekit_relationship.handler.relationship_assignment.class:               Mekit\Bundle\RelationshipBundle\Form\Handler\RelationshipAssignmentHandler
    mekit_relationship.handler.referenceable_element_search.class:          Mekit\Bundle\RelationshipBundle\Form\Handler\ReferenceableElementSearchHandler

    mekit_relationship.listener.referenceable_element_type.class:           Mekit\Bundle\RelationshipBundle\EventListener\ReferenceableElementTypeListener

services:
    mekit_relationship.form.relationship_assignment:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["mekit_relationship_assign_form", "mekit_relationship_assign", null]

    mekit_relationship.form.type.relationship_assignment:
        class: %mekit_relationship.type.relationship_assignment.class%
        arguments:
        tags:
            - { name: form.type, alias: mekit_relationship_assign }

    mekit_relationship.form.handler.relationship_assignment:
        class: %mekit_relationship.handler.relationship_assignment.class%
        scope: request
        arguments:
            - @mekit_relationship.form.relationship_assignment
            - @request
            - @doctrine.orm.entity_manager
        tags:



    mekit_relationship.form.type.referenceable_element:
        class: %mekit_relationship.type.referenceable_element.class%
        arguments:
            - @mekit_relationship.reference_manager
        tags:
            - { name: form.type, alias: mekit_referenceable_element }


    mekit_relationship.form.handler.referenceable_element_select:
        class: %mekit_relationship.handler.referenceable_element_search.class%
        calls:
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: referenceable_element_select, acl_resource: oro_search }


    mekit_relationship.form.type.referenceable_element_multi_select2:
        class: %mekit_relationship.type.referenceable_element_multi_select2.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: referenceable_element_multi_select2 }