parameters:
    mekit_relationship.reference_manager.class:                  Mekit\Bundle\RelationshipBundle\Entity\Manager\ReferenceManager

services:
    mekit_relationship.reference_manager:
        class: %mekit_relationship.reference_manager.class%
        arguments:
            - @oro_entity_config.config_manager
            - @doctrine.orm.default_entity_manager
