parameters:
    mekit_relationship.reference_manager.class:                  Mekit\Bundle\RelationshipBundle\Entity\Manager\ReferenceManager
    mekit_relationship.listener.entity_listener.class:           Mekit\Bundle\RelationshipBundle\EventListener\DoctrineListener

services:
    mekit_relationship.listener.entity_listener:
        class: %mekit_relationship.listener.entity_listener.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    mekit_relationship.reference_manager:
        class: %mekit_relationship.reference_manager.class%
        arguments:
            - @oro_entity_config.config_manager
            - @doctrine.orm.default_entity_manager


