Mekit\Bundle\RelationshipBundle\Entity\ReferenceableElement:
    alias:                          referenceable_element
    title_fields:                   [id, type]
#    route:
#        name:                       oro_user_view
#        parameters:
#            id:                     id
    search_template:                MekitRelationshipBundle:ReferenceableElement:Autocomplete/result.html.twig
    fields:
        -
            name:                   type
            target_type:            text
            target_fields:          [type]
