parameters:
#    mekit_relationship.example.class: Mekit\Bundle\RelationshipBundle\Example

services:
#    mekit_relationship.example:
#        class: %mekit_relationship.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
