datagrid:
    events-grid:
        extended_entity_name: %mekit_event.event.entity.class%
        source:
            type: orm
            query:
                select:
                    - e.id
                    - e.type
                    - >
                        CASE
                            WHEN evTask IS NOT NULL THEN evTask.id
                            WHEN evCall IS NOT NULL THEN evCall.id
                            WHEN evMeeting IS NOT NULL THEN evMeeting.id
                            ELSE ''
                            END as linkRefId
                    - >
                        CASE
                            WHEN evTask IS NOT NULL THEN evTask.name
                            WHEN evCall IS NOT NULL THEN evCall.name
                            WHEN evMeeting IS NOT NULL THEN evMeeting.name
                            ELSE ''
                            END as eventName
                    - ((CASE WHEN e.endDate IS NULL THEN 50 ELSE 100+DATE_DIFF(CURRENT_DATE(), e.endDate) END) * (CASE WHEN eventPriority.name = 'EVENT_PRIORITY_LOW' THEN 1 WHEN eventPriority.name = 'EVENT_PRIORITY_NORMAL' THEN 2 WHEN eventPriority.name = 'EVENT_PRIORITY_HIGH' THEN 3 ELSE 1 END)) as urgency
                    - (CASE WHEN e.endDate IS NULL THEN 'N/A' ELSE DATE_DIFF(e.endDate, CURRENT_DATE()) END) as dueInDays
                from:
                    - { table: %mekit_event.event.entity.class%, alias: e }
                join:
                    left:
                        - { join: e.state, alias: eventState }
                        - { join: e.priority, alias: eventPriority }
                        - { join: e.task, alias: evTask }
                        - { join: e.call, alias: evCall }
                        - { join: e.meeting, alias: evMeeting }

                        - { join: evTask.users, alias: taskUsers }
                        - { join: evCall.users, alias: callUsers }
                        - { join: evMeeting.users, alias: meetingUsers }
                where:
                    and:
                        - eventState.name = 'EVENT_STATE_ACTIVE'
                        - (taskUsers.id = @oro_security.security_facade->getLoggedUserId OR callUsers.id = @oro_security.security_facade->getLoggedUserId OR meetingUsers.id = @oro_security.security_facade->getLoggedUserId)

                orderBy:
                    - { column: urgency, dir: desc}
        columns:
            linked_icon_name:
                data_name:      type
                label:          false
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventIconLink.html.twig
                context:
                    config_route_key:     view_route_name
            dueInDays:
                label:          mekit.event.dashboard.my_active_events.column.due_in_days

        options:
            entityHint: event
            toolbarOptions:
                hide: true
                pageSize:
                    items: [5]
                    default_per_page: 5
