datagrid:
    events-grid:
        extended_entity_name: %mekit_event.event.entity.class%
        source:
            type:           orm
            query:
                select:
                    - e.id
                    - e.type
                    - e.endDate
                    - eventPriority.label as priority
                    - >
                        CASE
                            WHEN evTask IS NOT NULL THEN evTask.id
                            WHEN evCall IS NOT NULL THEN evCall.id
                            WHEN evMeeting IS NOT NULL THEN evMeeting.id
                            ELSE ''
                            END as linkRefId
                    - >
                        CASE
                            WHEN evTask IS NOT NULL THEN evTask.name
                            WHEN evCall IS NOT NULL THEN evCall.name
                            WHEN evMeeting IS NOT NULL THEN evMeeting.name
                            ELSE ''
                            END as eventName

                from:
                    - { table: %mekit_event.event.entity.class%, alias: e }
                join:
                    left:
                        - { join: e.state, alias: eventState }
                        - { join: e.priority, alias: eventPriority }
                        - { join: e.task, alias: evTask }
                        - { join: e.call, alias: evCall }
                        - { join: e.meeting, alias: evMeeting }

                        - { join: evTask.users, alias: taskUsers }
                        - { join: evCall.users, alias: callUsers }
                        - { join: evMeeting.users, alias: meetingUsers }
                where:
                    and:
                        - eventState.name = 'EVENT_STATE_ACTIVE'
                        - (taskUsers.id = @oro_security.security_facade->getLoggedUserId OR callUsers.id = @oro_security.security_facade->getLoggedUserId OR meetingUsers.id = @oro_security.security_facade->getLoggedUserId)
        columns:
            type_icon:
                data_name:      type
                label:          mekit.event.type.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventIcon.html.twig
            linked_name:
                data_name:      type
                label:          mekit.task.name.label
                type:           twig
                frontend_type:  html
                template:       MekitEventBundle:Event:Datagrid/Property/eventLink.html.twig
                context:
                    config_route_key:     view_route_name
            priority:
                label:         mekit.event.priority.label
            endDate:
                label:         mekit.event.end_date.label
                frontend_type: date
        sorters:
            columns:
                priority:
                    data_name: eventPriority.name
                endDate:
                    data_name: e.endDate
            default:
                endDate: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        options:
            entityHint: event
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
