oro_menu_config:
    items:
        events_tab:
            label: 'mekit.event.menu.events_tab.label'
            uri: '#'
            extras:
                icon: icon-group
                position: 19
