parameters:
#    mekit_event.example.class: Mekit\Bundle\EventBundle\Example

services:
#    mekit_event.example:
#        class: %mekit_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
