parameters:
    mekit_event.twig.extension.event_type_specific.class: Mekit\Bundle\EventBundle\Twig\EventTypeSpecific

services:
    mekit_event.twig.extension.event_type_specific:
        class: %mekit_event.twig.extension.event_type_specific.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

