Mekit\Bundle\EventBundle\Entity\Event:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        startDate:
            - NotBlank: ~
            - DateTime: ~
        endDate:
            - DateTime: ~
        duration:
            - Type:
                type: numeric
                message: The value {{ value }} is not a valid {{ type }}


