mekit_contact_info_bundle:
    resource:     "@MekitContactInfoBundle/Controller"
    type:         annotation
    prefix:       /contactinfo

mekit_contact_info_bundle_api:
    resource: "@MekitContactInfoBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest