mekit_project_bundle:
    resource:     "@MekitProjectBundle/Controller"
    type:         annotation
    prefix:       /project

mekit_project_bundle_api:
    resource: "@MekitProjectBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest