parameters:
    mekit_call.call.entity.class:                 Mekit\Bundle\CallBundle\Entity\Call
    mekit_call.placeholder.filter.class:          Mekit\Bundle\CallBundle\Placeholder\PlaceholderFilter

    mekit_call.provider.calendar.class:           Mekit\Bundle\CallBundle\Provider\CallCalendarProvider
    mekit_call.provider.normalizer.class:         Mekit\Bundle\CallBundle\Provider\CallCalendarNormalizer


services:
    mekit_call.autocomplete.call.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %mekit_call.call.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: mekit_call, acl_resource: mekit_call_view }

    mekit_call.placeholder.filter:
        class: %mekit_call.placeholder.filter.class%
        arguments:
            - @mekit_crm.relationship.manager

    mekit_call.provider.calendar:
        class: %mekit_call.provider.calendar.class%
        arguments:
            - @oro_entity.doctrine_helper
            - @oro_security.acl_helper
            - @mekit_call.provider.normalizer
            - @translator
        tags:
            - { name: oro_calendar.calendar_provider, alias: calls }

    mekit_call.provider.normalizer:
        class: %mekit_call.provider.normalizer.class%
        arguments:
            - @oro_reminder.entity.manager