datagrid:
    worklogs-related-to-task:
        extended_entity_name: %mekit_worklog.worklog.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_task_view
            query:
                select:
                    - wl.id
                    - wl.executionDate
                    - wl.duration
                    - wl.description
                    - wlOwner.firstName as ownerName
                from:
                    - { table: %mekit_worklog.worklog.entity.class%, alias: wl }
                join:
                    inner:
                        - { join: wl.task, alias: t }
                        - { join: wl.owner, alias: wlOwner }
                where:
                    and:
                        - t.id = :ref_id
            bind_parameters:
                - ref_id
        columns:
            executionDate:
                label:         mekit.worklog.execution_date.label
                frontend_type: date
            ownerName:
                label:         mekit.worklog.owner.label
            description:
                label:         mekit.worklog.description.label
            duration:
                label:         mekit.worklog.duration.label
        properties:
            id: ~
            update_link:
                type:       url
                route:      mekit_worklog_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      mekit_api_delete_worklog
                params:
                    id: id
        actions:
            update:
                type:          dialog
                acl_resource:  mekit_worklog_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  mekit_worklog_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link