Mekit\Bundle\WorklogBundle\Entity\Worklog:
    properties:
        executionDate:
            - NotBlank: ~
            - Date: ~
        duration:
            - NotBlank: ~
            - Regex:
                pattern: '/^[0-9]*(:[0-9]+)?$/'
                message: mekit.worklog.validation.duration.regex.message
        description:
            - NotBlank: ~
        owner:
            - NotBlank: ~
        task:
            - NotBlank: ~