datagrid:
    contacts-grid:
        extended_entity_name: %mekit_contact.contact.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_contact_view
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                    - CONCAT(Owner.firstName, CONCAT(' ', Owner.lastName)) as ownerName
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: c }
                join:
                    left:
                        - { join: c.owner, alias: Owner }
                groupBy: c.id

        columns:
            lastName:
                label:         mekit.contact.last_name.label
            firstName:
                label:         mekit.contact.first_name.label

        sorters:
            columns:
                firstName:
                    data_name: c.firstName
                lastName:
                    data_name: c.lastName
            default:
                lastName:  %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                firstName:
                    type: string
                    data_name: c.firstName
                lastName:
                    type: string
                    data_name: c.lastName

        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_contact_view
                params:     [ id ]
            update_link:
                type:       url
                route:      mekit_contact_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      mekit_api_delete_contact
                params:     [ id ]

        actions:
            view:
                type:          navigate
                acl_resource:  mekit_contact_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  mekit_contact_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  mekit_contact_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link

        mass_actions:
            delete:
                type: delete
                entity_name: %mekit_contact.contact.entity.class%
                data_identifier: c.id
                acl_resource: mekit_contact_delete
                label: oro.grid.action.delete
                icon: trash

        options:
            entityHint: contact
            export: true


    # 1) Extending datagrid MUST declare the FROM table with alias "baseEntity" which MUST have "contacts" relationship
    # 2) parameter "ref_id" identifying the "baseEntity" must be defined
    contacts-related-generic:
        extended_entity_name: %mekit_contact.contact.entity.class%
        source:
            type:           orm
            acl_resource:   mekit_contact_view
            query:
                select:
                    - c.id
                    - c.firstName
                    - c.lastName
                join:
                    inner:
                        - { join: baseEntity.contacts, alias: c }
                where:
                    and:
                        - baseEntity.id = :ref_id
            bind_parameters:
                - ref_id
        columns:
            lastName:
                label:         mekit.contact.last_name.label
            firstName:
                label:         mekit.contact.first_name.label
        properties:
            id: ~
            view_link:
                type:       url
                route:      mekit_contact_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  mekit_contact_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true

    contacts-related-users:
        extends: crm-related-users
        source:
            query:
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: baseEntity }

    contacts-related-accounts:
        extends: accounts-related-generic
        source:
            query:
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: baseEntity }

    contacts-related-tasks:
        extends: tasks-related-generic
        source:
            query:
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: baseEntity }

    contacts-related-calls:
        extends: calls-related-generic
        source:
            query:
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: baseEntity }

    contacts-related-meetings:
        extends: meetings-related-generic
        source:
            query:
                from:
                    - { table: %mekit_contact.contact.entity.class%, alias: baseEntity }