parameters:
    mekit_contact.importexport.normalizer.contact.class:                  Mekit\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\ContactNormalizer
    mekit_contact.importexport.strategy.contact.add_or_replace.class:     Mekit\Bundle\ContactBundle\ImportExport\Strategy\ContactAddOrReplaceStrategy
    mekit_contact.importexport.strategy.contact.add.class:                Mekit\Bundle\ContactBundle\ImportExport\Strategy\ContactAddStrategy
    mekit_contact.importexport.helper.contact_import_helper.class:        Mekit\Bundle\ContactBundle\ImportExport\Strategy\ContactImportHelper
    mekit_contact.importexport.template_fixture.contact.class:            Mekit\Bundle\ContactBundle\ImportExport\TemplateFixture\ContactFixture

services:
    mekit_contact.importexport.template_fixture.contact:
        class: %mekit_contact.importexport.template_fixture.contact.class%
        tags:
            - { name: oro_importexport.template_fixture }

    # Normalizers
    mekit_contact.importexport.normalizer.contact:
        class: %mekit_contact.importexport.normalizer.contact.class%
        parent: oro_importexport.serializer.configurable_entity_normalizer
        calls:
            - [setSocialUrlFormatter, [@mekit_contact.social_url_formatter]]
        tags:
            - { name: oro_importexport.normalizer }

    # Converter
    mekit_contact.importexport.data_converter.contact:
        parent: oro_importexport.data_converter.configurable

    mekit_contact.importexport.template_fixture.data_converter.contact:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    mekit_contact.importexport.strategy.contact.add_or_replace:
        class: %mekit_contact.importexport.strategy.contact.add_or_replace.class%
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setContactImportHelper, [@mekit_contact.importexport.helper.contact_import_helper]]

    mekit_contact.importexport.strategy.contact.add:
        class: %mekit_contact.importexport.strategy.contact.add.class%
        parent: oro_importexport.strategy.add
        calls:
            - [setContactImportHelper, [@mekit_contact.importexport.helper.contact_import_helper]]
            - [setSecurityContext, [@security.context]]

    # Import processor
    mekit_contact.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@mekit_contact.importexport.data_converter.contact]]
            - [setStrategy, [@mekit_contact.importexport.strategy.contact.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact.add_or_replace }

    mekit_contact.importexport.processor.import.add:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, [@mekit_contact.importexport.data_converter.contact]]
            - [setStrategy, [@mekit_contact.importexport.strategy.contact.add]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact.add }
            - { name: oro_importexport.processor, type: import_validation, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact.add }

    # Export processor
    mekit_contact.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mekit_contact.importexport.data_converter.contact]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact }

    mekit_contact.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@mekit_contact.importexport.template_fixture.data_converter.contact]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %mekit_contact.contact.entity.class%, alias: mekit_contact }

    # Helper
    mekit_contact.importexport.helper.contact_import_helper:
        class: %mekit_contact.importexport.helper.contact_import_helper.class%
