parameters:
#    mekit_contact.example.class: Mekit\Bundle\ContactBundle\Example

services:
#    mekit_contact.example:
#        class: %mekit_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
