workflows:
    opportunity:
        steps:
            qualify:
                label: 'Qualify'
                order: 10
                allowed_transitions:
                    - develop
            develop:
                label: 'Develop'
                order: 20
                entity_acl:
                    opportunity_amount:
                        update: false
                allowed_transitions:
                    - close_as_won
                    - close_as_lost
            close:
                label: 'Closed'
                order: 30
                allowed_transitions:
                    - requalify_lost
                    - requalify_won
                is_final: true
