workflows:
    opportunity:
        transition_definitions:
            qualify_definition:
                pre_conditions:
                    @equal: [$opportunity.state.name, 'OPPORTUNITY_STATE_IN_PROGRESS']

            develop_definition:
                pre_conditions:
                    @equal:
                        message: 'Opportunity state must be "In progress"'
                        parameters: [$opportunity.state.name, 'OPPORTUNITY_STATE_IN_PROGRESS']
                conditions:
                    @and:
                        - @greater_or_equal:
                            message: 'Amount must be greater or equal to 0'
                            parameters: [$opportunity_amount, 0]
                        - @and:
                            message: 'Probality must be between 0 and 100'
                            parameters:
                                - @greater_or_equal: [$opportunity_probability, 0]
                                - @less_or_equal: [$opportunity_probability, 1]

            close_as_won_definition:
                pre_conditions:
                    @equal:
                        message: 'Opportunity state must be "In progress"'
                        parameters: [$opportunity.state.name, 'OPPORTUNITY_STATE_IN_PROGRESS']
#                conditions:
#                    @and:
#                        - @not_empty:
#                            message: 'Close date must be set'
#                            parameters: $close_date
#                        - @not_empty:
#                            message: 'Close revenue must be set'
#                            parameters: $close_revenue
#                        - @greater_or_equal:
#                            message: 'Close revenue must be greater or equal to 0'
#                            parameters: [$close_revenue, 0]
#                post_actions: # update opportunity properties, set opportunity.status = "won"
#                    - @find_entity:
#                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
#                        identifier: 'won'
#                        attribute: $opportunity.status
#                    - @find_entity:
#                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
#                        identifier: 'won'
#                        attribute: $close_reason
#                    - @assign_value:
#                        - [$probability, 1]
#                        - [$close_reason_name, 'won']

            close_as_lost_definition:
                pre_conditions:
                    @equal:
                        message: 'Opportunity state must be "In progress"'
                        parameters: [$opportunity.state.name, 'OPPORTUNITY_STATE_IN_PROGRESS']
                conditions:
                    @and:
                        - @not_empty:
                            message: 'Close date must be set'
                            parameters: $close_date
                        - @not_empty:
                            message: 'Close reason must be set'
                            parameters: $close_reason_name
                post_actions: # update opportunity properties, set opportunity.status = "lost"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
                        identifier: 'lost'
                        attribute: $opportunity.status
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
                        identifier: $close_reason_name
                        attribute: $close_reason
                    - @assign_value:
                        - [$probability, 0]
                        - [$close_revenue, 0]

            requalify_lost_definition:
                conditions:
                    @equal: [$opportunity.state.name, 'OPPORTUNITY_STATE_LOST']
#                post_actions:
#                    - @find_entity:
#                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
#                        identifier: 'in_progress'
#                        attribute: $opportunity.status
#                    - @assign_value:
#                        - [$budget_amount, ~]
#                        - [$probability, ~]
#                        - [$close_reason, ~]
#                        - [$close_date, ~]
#                        - [$close_revenue, ~]

            requalify_won_definition:
                conditions:
                    @equal: [$opportunity.state.name, 'OPPORTUNITY_STATE_WON']
#                post_actions:
#                    - @find_entity:
#                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
#                        identifier: 'in_progress'
#                        attribute: $opportunity.status
