mekit_meeting_bundle:
    resource:     "@MekitMeetingBundle/Controller"
    type:         annotation
    prefix:       /meeting

mekit_meeting_bundle_api:
    resource: "@MekitMeetingBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
